Only allow real session files in commands and completion

diff --git a/libexec/__pfm-conninfo b/libexec/__pfm-conninfo
--- a/libexec/__pfm-conninfo
+++ b/libexec/__pfm-conninfo
@@ -15,6 +15,12 @@ __pfm-conninfo() {
         return 2
     fi
 
+    if ! [[ "$connfile" =~ = ]]
+    then
+      echo "Invalid session file: $connfile" >&2
+      return 1
+    fi
+
     local fname; fname=$(basename "$connfile")
     read -r ssh_host ftype from_port to_host to_port <<< "${fname//=/ }"
 
diff --git a/libexec/__pfm-list b/libexec/__pfm-list
--- a/libexec/__pfm-list
+++ b/libexec/__pfm-list
@@ -35,6 +35,12 @@ __pfm-list() {
         local s
         for s in "$PFM_SESSIONS"/"${ignoremarker}"* "$@"
         do
+            if ! [[ "$s" =~ = ]]
+            then
+              echo "Invalid session file: $s" >&2
+              continue
+            fi
+
             read -r state ssh_host ftype from_port to_host to_port s_real desc <<< "$(__pfm-conninfo conninfo "$s")"
             : "$from_port" "$to_host" "$to_port" # ignored
             if [[ "$last_hosttype" != "${ssh_host} [$ftype]" ]]
diff --git a/libexec/__pfm-stop b/libexec/__pfm-stop
--- a/libexec/__pfm-stop
+++ b/libexec/__pfm-stop
@@ -21,6 +21,12 @@ __pfm-stop() {
     then
         session_file=$2
 
+        if ! [[ "$session_file" =~ = ]]
+        then
+          echo "Invalid session file: $session_file" >&2
+          return 1
+        fi
+
         if ! [ -S "$session_file" ] && [ -S "$PFM_SESSIONS/$session_file" ]
         then
             session_file="$PFM_SESSIONS/$session_file"
