No cleanup on repair, always create symlink first

diff --git a/libexec/__pfm-remote b/libexec/__pfm-remote
--- a/libexec/__pfm-remote
+++ b/libexec/__pfm-remote
@@ -39,25 +39,26 @@ __pfm-remote() {
         return 3
     fi
 
+    # create the link first as this is what we use to check for existing sessions and connection attempts
+    if ! ln -s "$session_socket" "$session_file"
+    then
+        echo "Failed to link unix socket for remote port $ssh_host:$ssh_port -> localhost -> $forward_host:$forward_port" >&2
+        [[ 1 == "$PFM_NOCLEANUP" ]] || __pfm-stop stop - "$session_file" || :
+        return 6
+    fi
+
     if ! ssh -M -S "$session_socket" -fnNT "$ssh_host"
     then
         echo "Failed to establish connection to $ssh_host" >&2
-        __pfm-stop stop - "$session_socket" || :
+        [[ 1 == "$PFM_NOCLEANUP" ]] || __pfm-stop stop - "$session_file" || :
         return 4
     fi
 
     if ! ssh -S "$session_socket" -O forward -R "$ssh_port:$forward_host:$forward_port" "$ssh_host"
     then
         echo "Failed to forward remote port $ssh_host:$ssh_port -> localhost -> $forward_host:$forward_port" >&2
-        __pfm-stop stop - "$session_socket" || :
+        [[ 1 == "$PFM_NOCLEANUP" ]] || __pfm-stop stop - "$session_file" || :
         return 5
-    fi
-
-    if ! ln -s "$session_socket" "$session_file"
-    then
-        echo "Failed to link unix socket for remote port $ssh_host:$ssh_port -> localhost -> $forward_host:$forward_port" >&2
-        __pfm-stop stop - "$session_socket" || :
-        return 6
     fi
 }
 
