Improve local ux, better list and doctor output

diff --git a/libexec/pfm-local b/libexec/pfm-local
--- a/libexec/pfm-local
+++ b/libexec/pfm-local
@@ -8,35 +8,46 @@ pfm-local() {
     fi
     shift 1
 
-    local host=$1
-    local lport=$2
-    local rport=${3:-$lport}
+    local lport=$1
+    local ssh_host=$2
+    local rhost
+    local rport
+
+    if [ -z "$3" ]
+    then
+        rhost=$ssh_host
+        rport=$lport
+    elif [ -z "$4" ]
+    then
+        rhost=$ssh_host
+        rport=$3
+    fi
     # TODO check PFM_SESSIONS exists, check is created, create if missing, warnings and exit if not
     
     if [ -z "$rport" ]
     then
-        echo "Usage: pfm local <host> <lport> [rport]"
+        echo "Usage: pfm local <local port> <ssh host> [remote host [remote port]]"
         return 2
     fi
 
-    local session_file="$PFM_SESSIONS/${host}_local_${lport}_${rport}"
+    local session_file="$PFM_SESSIONS/${ssh_host}=local=${lport}=${rhost}=${rport}"
     if [ -e "$session_file" ]
     then
-        echo "Session already exists for localhost:$lport -> $host:$rport"
+        echo "Session already exists for $lport -> $ssh_host -> $rhost:$rport"
         return 3
     fi
 
-    if ! ssh -M -S "$session_file" -fnNT "$host"
+    if ! ssh -M -S "$session_file" -fnNT "$ssh_host"
     then
-        echo "Failed to establish connection to $host" >&2
-        pfm-stop stop - "$session_file" "$host" || :
+        echo "Failed to establish connection to $ssh_host" >&2
+        pfm-stop stop - "$session_file" || :
         return 4
     fi
 
-    if ! ssh -S "$session_file" -O forward -L "$lport:localhost:$rport" "$host"
+    if ! ssh -S "$session_file" -O forward -L "$lport:$rhost:$rport" "$ssh_host"
     then
-        echo "Failed to forward port $lport to $host:$rport" >&2
-        pfm-stop stop - "$session_file" "$host" || :
+        echo "Failed to forward port $lport -> $ssh_host -> $rhost:$rport" >&2
+        pfm-stop stop - "$session_file" || :
         return 5
     fi
 }
