Add pfm-remote, align and fix pfm-local

diff --git a/libexec/pfm-local b/libexec/pfm-local
--- a/libexec/pfm-local
+++ b/libexec/pfm-local
@@ -10,30 +10,29 @@ pfm-local() {
 
     local lport=$1
     local ssh_host=$2
-    local rhost
-    local rport
+    local rhost=$3
+    local rport=$4
 
     if [ -z "$3" ]
     then
-        rhost=$ssh_host
+        rhost=localhost
         rport=$lport
     elif [ -z "$4" ]
     then
         rhost=localhost
         rport=$3
     fi
-    # TODO check PFM_SESSIONS exists, check is created, create if missing, warnings and exit if not
     
     if [ -z "$rport" ]
     then
-        echo "Usage: pfm local <local port> <ssh host> [remote host [remote port]]"
+        echo "Usage: pfm local <local port> <ssh host> [remote host [remote port]]" >&2
         return 2
     fi
 
     local session_file="$PFM_SESSIONS/${ssh_host}=local=${lport}=${rhost}=${rport}"
     if [ -e "$session_file" ]
     then
-        echo "Session already exists for $lport -> $ssh_host -> $rhost:$rport"
+        echo "Session already exists for localhost:$lport -> $ssh_host -> $rhost:$rport" >&2
         return 3
     fi
 
@@ -46,7 +45,7 @@ pfm-local() {
 
     if ! ssh -S "$session_file" -O forward -L "$lport:$rhost:$rport" "$ssh_host"
     then
-        echo "Failed to forward port $lport -> $ssh_host -> $rhost:$rport" >&2
+        echo "Failed to forward local port localhost:$lport -> $ssh_host -> $rhost:$rport" >&2
         pfm-stop stop - "$session_file" || :
         return 5
     fi
